hbase:
 image: utcn/hbase
 container_name: prod_hbase
 hostname: hbase_readonly
 ports:
 - "2181:2181"
 - "16000-16100:16000-16100"
 - "8080:8080"
 volumes:
 - ./hbase/hbase:/opt/hbase-data
 - ./hbase/conf:/opt/hbase/conf
 - ./ssh/keys:/etc/ssh/keys

tsdb_rw:
 image: utcn/tsdb:2.2.0
 container_name: prod_tsdb_rw
 hostname: tsdb_rw
 ports:
 - "4242:4242"
 volumes:
 - ./tsdb/rw/cache:/opt/data/cache
 - ./tsdb/rw/tsdb:/opt/data/tsdb
 - ./ssh/keys:/etc/ssh/keys
 links:
 - hbase

grafana:
 image: grafana/grafana
 container_name: grafana
 hostname: grafana_rw
 ports:
 - "3000:3000"
 volumes:
 - ./grafana:/var/lib/grafana
 links:
 - tsdb_rw
 - tsdb_ro_1
 - tsdb_ro_2
 - tsdb_ro_3

tsdb_ro_1:
 image: utcn/tsdb:2.2.0
 container_name: prod_tsdb_ro_1
 hostname: tsdb_ro_1
 volumes:
 - ./tsdb/ro-1/cache:/opt/data/cache
 - ./tsdb/ro-1/tsdb:/opt/data/tsdb
 - ./ssh/keys:/etc/ssh/keys
 links:
 - hbase

tsdb_ro_2:
 image: utcn/tsdb:2.2.0
 container_name: prod_tsdb_ro_2
 hostname: tsdb_ro_2
 volumes:
 - ./tsdb/ro-2/cache:/opt/data/cache
 - ./tsdb/ro-2/tsdb:/opt/data/tsdb
 - ./ssh/keys:/etc/ssh/keys
 links:
 - hbase

tsdb_ro_3:
 image: utcn/tsdb:2.2.0
 container_name: prod_tsdb_ro_3
 hostname: tsdb_ro_3
 volumes:
 - ./tsdb/ro-3/cache:/opt/data/cache
 - ./tsdb/ro-3/tsdb:/opt/data/tsdb
 - ./ssh/keys:/etc/ssh/keys
 links:
 - hbase

icinga2:
 image: utcn/icinga2
 container_name: docker_icinga2
 hostname: icinga2-master
 ports:
 - "80:80"
 - "443:443"
 - "5665:5665"
 - "3306:3306"
 volumes:
 - ./icinga2/etc/icinga2:/etc/icinga2
 links:
 - hbase
 - tsdb_rw
 - tsdb_ro_1
 - tsdb_ro_2
 - tsdb_ro_3
 - tcollector_1
 - tcollector_2
 environment:
 - ICINGA_PASSWORD=icinga
 - ICINGA_WEB_PASSWORD=icinga
 - ICINGAWEB2_PASSWORD=icinga
 - IDO_PASSWORD=icinga

varnish:
 image: eeacms/varnish:3
 container_name: varnish
 hostname: varnish
 ports:
 - "4343:80"
 volumes:
 - ./varnish:/etc/varnish/conf.d
 links:
 - tsdb_ro_1:tsd_tsdb_ro_1
 - tsdb_ro_2:tsd_tsdb_ro_2
 - tsdb_ro_3:tsd_tsdb_ro_3
 environment:
 - CACHE_SIZE=1024m

tcollector_1:
 image: utcn/tcollector
 container_name: prod_tcollector_1
 hostname: tcollector_1
 volumes:
 - ./tcollector/data/dump_1:/opt/data/dump
 - ./ssh/keys:/etc/ssh/keys
 links:
 - tsdb_rw:tsdb

tcollector_2:
 image: utcn/tcollector
 container_name: prod_tcollector_2
 hostname: tcollector_2
 volumes:
 - ./tcollector/data/dump_2:/opt/data/dump
 - ./ssh/keys:/etc/ssh/keys
 links:
 - tsdb_rw:tsdb
